name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: arn:aws:iam::593537320251:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}


      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: bedrock-gateway
          platform: linux/arm64
          enableBuildKit: true
          tags: v1
          registry: 593537320251.dkr.ecr.ap-south-1.amazonaws.com
          dockerfile: ./src/Dockerfile_ecs 
